# Generated by Django 5.1.6 on 2025-06-06 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_item_quantity_alter_purchaseitem_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_suffix',
            field=models.CharField(blank=True, help_text='Enter the suffix only', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rrn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
