# Generated by Django 5.1.6 on 2025-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_invoice_invoice_suffix_alter_invoice_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
